- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create EFS volume
      efs:
        state: present
        name: "{{ efs_name }}"
        tags:
          name: "{{ efs_name }}"
          purpose: file-storage
        targets:
          - subnet_id: "{{ efs_subnet_id }}"
            security_groups: [ "{{ efs_sec_grp }}" ]
      register: efs

    - set_stats:
        data:
          security_group_id: "{{ efs.id }}"
