- hosts: localhost
  connection: local
  gather_facts: True

  vars:
    security_group_name: "{{business_unit}}-{{application_environment}}-{{pod_name}}-MONITOR-SG"

  tasks:
    - name: Create aws security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Security group
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        tags:
            Name: "{{ security_group_name }}"
            APPLICATIONENV: "{{ application_environment }}"
            APPLICATIONROLE: "{{ application_role }}"
            BUSINESSENTITY: "{{ business_entity }}"
            BUSINESSUNIT: "{{ business_unit }}"
            DOMAIN: "{{ domain }}"
            ENVIRONMENT: "{{ pod_environment }}"
            OWNEREMAIL: "{{ owner_email }}"
            POD: "{{ pod_name}}"
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: "{{ cidr_blocks_nagios }}"
            rule_desc: "Nagios MySQL Port"
          - proto: tcp
            from_port: 5666
            to_port: 5666
            cidr_ip: "{{ cidr_blocks_nagios }}"
            rule_desc: "Nagios Server Port"
          - proto: tcp
            from_port: 8301
            to_port: 8301
            cidr_ip: "{{ cidr_blocks_ma }}"
            rule_desc: "Consul TCP Port"
          - proto: udp
            from_port: 8301
            to_port: 8301
            cidr_ip: "{{ cidr_blocks_ma }}"
            rule_desc: "Consul UDP Port"
      when: security_group_name != ""
      register: security_group

    - set_stats:
        data:
          security_group_id: "{{ security_group.group_id }}"
      when: security_group_name != ""
