- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Create aws security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Security group
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        tags:
            Name: "{{ security_group_name }}"
            APPLICATIONENV: "{{ application_environment }}"
            APPLICATIONROLE: "{{ application_role }}"
            BUSINESSENTITY: "{{ business_entity }}"
            BUSINESSUNIT: "{{ business_unit }}"
            DOMAIN: "{{ domain }}"
            ENVIRONMENT: "{{ pod_environment }}"
            OWNEREMAIL: "{{ owner_email }}"
            POD: "{{ pod_name}}"
            RUNNINGSCHEDULE: "{{ running_schedule }}"
            SERVICEENTITY: "{{ service_entity }}"
            SERVICENAME: "{{ service_name }}"
            SHORT_HOSTNAME: "{{ short_hostname }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ cidr_access }}"
      when: security_group_name != ""
      register: security_group

    - set_fact:
        cacheable: true
        security_group_id: "{{ security_group.group_id }}"
      when: security_group_name != ""
