- hosts: localhost
  connection: local
  gather_facts: True

  vars:
    ids_db_name: "intcloud-{{ENVIRONMENT}}-ids-rds"

  tasks:
   - name: Provision a new rds instance
     rds:
       command: create
       instance_name: "{{ ids_db_name }}"
       db_engine: MySQL
       size: "{{ ids_allocated_storage }}"
       instance_type: "{{ ids_rds_instance_type }}"
       username: "{{ ids_rds_username }}"
       password: "{{ ids_rds_password }}"
       upgrade: no
       parameter_group: "{{ids_parameter_group_name}}"
       vpc_security_groups:
         - "{{db_security_group_id}}"
         - "{{monitor_security_group_id}}"
       backup_retention: 7
       subnet:
       tags:
            Name: "{{ ids_db_name }}"
            APPLICATIONENV: "{{ application_environment }}"
            APPLICATIONROLE: "{{ application_role }}"
            BUSINESSENTITY: "{{ business_entity }}"
            BUSINESSUNIT: "{{ business_unit }}"
            DOMAIN: "{{ domain }}"
            ENVIRONMENT: "{{ pod_environment }}"
            OWNEREMAIL: "{{ owner_email }}"
            POD: "{{ pod_name}}"
            RUNNINGSCHEDULE: "{{ running_schedule }}"
    register: maids_rds
