- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
   - name: "Output test results"
     debug:
       msg: "{{ security_group_id }}"

   - name: Provision a set of instances
     ec2:
         key_name: "{{ key_name }}"
         region: "{{ aws_region }}"
         instance_type: "{{ instance_type }}"
         image: "{{ aws_ami }}"
         group: "{{ security_group_name }}"
         wait: true
         instance_tags:
            Name: "{{ instance_name }}"
            APPLICATIONENV: "{{ application_environment }}"
            APPLICATIONROLE: "{{ application_role }}"
            BUSINESSENTITY: "{{ business_entity }}"
            BUSINESSUNIT: "{{ business_unit }}"
            DOMAIN: "{{ domain }}"
            ENVIRONMENT: "{{ pod_environment }}"
            OWNEREMAIL: "{{ owner_email }}"
            POD: "{{ pod_name}}"
            RUNNINGSCHEDULE: "{{ running_schedule }}"
            SERVICEENTITY: "{{ service_entity }}"
            SERVICENAME: "{{ service_name }}"
            SHORT_HOSTNAME: "{{ short_hostname }}"
     register: ec2

   - set_stats:
       data:  
         host_ip: "{{ item.private_ip }}"
     loop: "{{ ec2.instances }}"

